# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('greeting', models.TextField(blank=True, null=True)),
                ('number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
